#pragma config(Motor,  port2,           right1,        tmotorVex393, openLoop)
#pragma config(Motor,  port3,           right2,        tmotorVex393, openLoop)
#pragma config(Motor,  port7,           left1,         tmotorVex393, openLoop)
#pragma config(Motor,  port8,           left2,         tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{



}

void linearMove(int power) {
	//int power
}

void turn() {

}

vo
